services:
  mysql:
    container_name: demo2_mysql
    image: mysql:8.0.40
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo2
      - MYSQL_USER=demo2
      - MYSQL_PASSWORD=demo2
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - internal
    ports:
      - 3307:3306

  app:
    container_name: demo2_app
    image: demo2_app:latest
    restart: on-failure
    networks:
      - internal
    depends_on:
      - mysql
    build:
      context: ../
      dockerfile: docker/Dockerfile_local
      target: app
      args:
        - ENV=local
    volumes:
      - ../storage:/app/storage

  queue_default:
    container_name: demo2_queue_default
    image: demo2_app:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile_local
      target: app
      args:
        - ENV=local
    depends_on:
      - app
    networks:
      - internal
    command: php artisan queue:work --daemon --queue=default --sleep=3 --tries=2
    volumes:
      - ../storage:/app/storage


networks:
  internal:
